// AUTOGENERATED TYPINGS, these should not be edited.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        container: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StyleCssNamespace.IStyleCss;
};

export = StyleCssModule;
