// AUTOGENERATED TYPINGS, these should not be edited.
declare namespace VariablesCssNamespace {
    export interface IVariablesCss {
        colors: string;
        entities: string;
        lightTheme: string;
        theme: string;
        variables: string;
    }
}

declare const VariablesCssModule: VariablesCssNamespace.IVariablesCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: VariablesCssNamespace.IVariablesCss;
};

export = VariablesCssModule;
