// AUTOGENERATED TYPINGS, these should not be edited.
declare namespace VariablesCssNamespace {
    export interface IVariablesCss {
        dark: string;
        light: string;
    }
}

declare const VariablesCssModule: VariablesCssNamespace.IVariablesCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: VariablesCssNamespace.IVariablesCss;
};

export = VariablesCssModule;
