// Webpack third party plugins
import HtmlWebPackPlugin from "html-webpack-plugin";
import CopyWebPackPlugin from "copy-webpack-plugin";

// minification
import TerserPlugin from "terser-webpack-plugin";

import { BundleAnalyzerPlugin } from "webpack-bundle-analyzer";
import WebpackBar from "webpackbar";

// Webpack first party plugins
import { Plugin, WatchIgnorePlugin } from "webpack";

// Utils

/** Handles the templating of index.html */
const htmlWebPackPlugin: HtmlWebPackPlugin = new HtmlWebPackPlugin({
    template: "./config/templates/index.html",
    filename: "./index.html",
});

const copyImages = new CopyWebPackPlugin([
    { from: "./resources/images/", to: "./resources/images/" },
]);

// Minify prod code
const uglify = new TerserPlugin({
    include: new RegExp("/build"),
});

const bundleAnalyzer = new BundleAnalyzerPlugin();

// Currently ignores all typings being autogenerated for less modules.
const ignoreTypings = new WatchIgnorePlugin([/less\.d\.ts$/]);

// Custom bundling stats.
const progressReport = new WebpackBar({
    name: "bearcave",
    color: "#007079",
    profile: true,
});

// Export all plugins which are used in all environments.
export const defineBasePlugins = (): Plugin[] => {
    return [htmlWebPackPlugin, copyImages, ignoreTypings, progressReport];
};
/**
 * Export individual plugins.
 */
export { htmlWebPackPlugin };
export { copyImages };
export { uglify };
export { bundleAnalyzer };
export { ignoreTypings };
