// Webpack third party plugins
const HtmlWebPackPlugin = require("html-webpack-plugin");
const CopyWebPackPlugin = require("copy-webpack-plugin");
// minification
const TerserPlugin = require("terser-webpack-plugin");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");
const WebpackBar = require("webpackbar");

// Webpack first party plugins

// Utils

/** Handles the templating of index.html */
const htmlWebPackPlugin = new HtmlWebPackPlugin({
    template: "./config/templates/index.html",
    filename: "./index.html",
});

const copyImages = new CopyWebPackPlugin({
    patterns: [{ from: "./resources/images/", to: "./resources/images/" }],
});

// Minify prod code
const uglify = new TerserPlugin({
    include: new RegExp("/build"),
});

const bundleAnalyzer = new BundleAnalyzerPlugin();

// Currently ignores all typings being autogenerated for less modules.
// const ignoreTypings = new WatchIgnorePlugin([/less\.d\.ts$/]);

// Custom bundling stats.
const progressReport = new WebpackBar({
    name: "bearcave",
    color: "#007079",
    profile: true,
});

// Export all plugins which are used in all environments.
module.exports = {
    htmlWebPackPlugin,
    copyImages,
    uglify,
    bundleAnalyzer,
    defineBasePlugins: function () {
        return [htmlWebPackPlugin, copyImages, progressReport];
    },
};
