import { RuleSetRule, Module } from "webpack";
import { join } from "path";
import { rootPath } from "./root";

let transpiler: RuleSetRule = {
    test: /\.(js|jsx|tsx|ts)$/,
    exclude: [/node_modules/, /build/],
    loader: "babel-loader",
    query: {
        cacheDirectory: true,
    },
};

let html: RuleSetRule = {
    test: /\.html$/,
    use: [{ loader: "html-loader" }],
};

let moduledLess: RuleSetRule = {
    test: /\.(less)$/,
    include: [join(rootPath, "/src/components")],
    use: [
        { loader: "style-loader" },
        {
            loader: "@teamsupercell/typings-for-css-modules-loader",
            options: { banner: "// AUTOGENERATED TYPINGS, these should not be edited.", eol: "\n" },
        },
        { loader: "css-loader", options: { modules: true } },
        { loader: "less-loader", options: { rewriteUrls: "local" } },
    ],
};

let less: RuleSetRule = {
    test: /\.(less)$/,
    include: [join(rootPath, "/src/app.less")],
    exclude: [join(rootPath, "/src/components")],
    use: [{ loader: "style-loader" }, { loader: "css-loader" }, { loader: "less-loader" }],
};

let css: RuleSetRule = {
    test: /\.css$/,
    exclude: [join(rootPath, "/src/components")],
    use: [{ loader: "style-loader" }, { loader: "css-loader" }],
};

let images: RuleSetRule = {
    test: /\.(png|jpg|gif|jpeg)$/,
    include: [join(rootPath, "/resources/images"), join(rootPath, "/node_modules/semantic-ui-css")],
    use: [
        {
            loader: "cache-loader",
        },
        {
            loader: "file-loader",
            options: {
                name: "[name].[ext]",
                outputPath: "./resources/images/",
            },
        },
    ],
};

let icons: RuleSetRule = {
    test: /\.svg$/,
    use: [
        {
            loader: "@svgr/webpack",
            options: {
                native: false,
            },
        },
        { loader: "url-loader" },
    ],
};

let fonts: RuleSetRule = {
    test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
    include: [
        join(rootPath, "/resources/fonts"),
        join(rootPath, "/node_modules/css-loader"),
        join(rootPath, "/node_modules/less-loader"),
    ],
    use: [
        {
            loader: "file-loader",
            options: {
                outputPath: "resources/fonts/",
                name: "[name].[ext]",
            },
        },
    ],
};

export const defineBaseRules = function(): Module {
    return { rules: [transpiler, html, moduledLess, less, css, images, icons, fonts] };
};
/**
 * Export as module
 */

/**
 * Export individual rules
 */
export { transpiler };
export { html };
export { less };
export { moduledLess };
export { css };
export { images };
export { icons };
export { fonts };
