const { rootPath, join } = require("./root");

const transpiler = {
    test: /\.(js|jsx|tsx|ts)$/,
    exclude: [/node_modules/, /build/],
    use: {
        loader: "babel-loader",
        options: {
            cacheDirectory: true,
        },
    },
};

const html = {
    test: /\.html$/,
    use: [{ loader: "html-loader" }],
};

const styles = {
    test: /\.(css)$/,
    include: [join(rootPath, "/src")],
    use: [
        "style-loader",
        {
            loader: "@teamsupercell/typings-for-css-modules-loader",
            options: {
                banner: "// AUTOGENERATED TYPINGS, these should not be edited.",
                eol: "\n",
            },
        },
        { loader: "css-loader", options: { modules: true } },
    ],
};

const images = {
    test: /\.(png|svg|jpg|gif|jpeg)$/,
    use: ["file-loader"],
};

module.exports = {
    // fonts,
    // icons,
    images,
    styles,
    html,
    transpiler,
    defineBaseRules: function () {
        const baserules = {
            rules: [transpiler, html, styles, images],
        };
        return baserules;
    },
};
