const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const { rootPath, join } = require("./root");

const transpiler = {
    test: /\.(js|jsx|tsx|ts)$/,
    exclude: [/node_modules/, /build/],
    use: {
        loader: "babel-loader",
        options: {
            cacheDirectory: true,
        },
    },
};

const html = {
    test: /\.html$/,
    use: ["html-loader"],
};

const devStyles = {
    test: /\.(css)$/,
    include: [join(rootPath, "/src")],
    use: [
        "style-loader",
        {
            loader: "@teamsupercell/typings-for-css-modules-loader",
            options: {
                banner: "// AUTOGENERATED TYPINGS, these should not be edited.",
                eol: "\n",
            },
        },
        { loader: "css-loader", options: { modules: true } },
    ],
};

const prodStyles = {
    test: /\.(css)$/,
    use: [
        MiniCssExtractPlugin.loader,
        { loader: "css-loader", options: { modules: true } },
    ],
};

const resources = {
    test: /\.(png|svg|jpg|gif|jpeg|ico)$/,
    use: ["file-loader"],
};

module.exports = {
    // fonts,
    // icons,
    resources,
    devStyles,
    prodStyles,
    html,
    transpiler,
    defineBaseRules: function () {
        return [transpiler, html, resources];
    },
};
