// AUTOGENERATED TYPINGS, these should not be edited.
declare namespace StylesCssNamespace {
    export interface IStylesCss {
        dialog: string;
        notsmall: string;
        root: string;
    }
}

declare const StylesCssModule: StylesCssNamespace.IStylesCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StylesCssNamespace.IStylesCss;
};

export = StylesCssModule;
