name: Firebase Deploy on push

on:
    push:
        branches:
            - master
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: build-prod
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOBZOR_32DAA }}"
                  channelId: live
                  projectId: tobzor-32daa
              env:
                  FIREBASE_CLI_PREVIEWS: hostingchannels
